spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: NGSIDatenbank
      uri: mongodb://localhost:27017/

server:
  port: 8080

logging:
  level:
    org.springframework.data.mongodb.core : DEBUG
